# Generated by Django 5.0.2 on 2024-02-12 17:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CategoriaCientifica',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.CharField(choices=[('master', 'Master'), ('doctor', 'Doctor')], max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='CategoriaDocente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.CharField(choices=[('instructor', 'Instructor'), ('asistente', 'Asistente'), ('auxiliar', 'Auxiliar'), ('titular', 'Titular')], max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='NivelEscolaridad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.CharField(choices=[('9no_grado', '9no Grado'), ('tecnico_medio', 'Técnico Medio'), ('12mo_grado', '12mo Grado'), ('universitario', 'Universitario')], max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='Trabajador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('apellidos', models.CharField(max_length=100)),
                ('carnet_identidad', models.IntegerField(default=0)),
                ('direcciion', models.TextField()),
                ('categoria_cientifica', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='RR_HH.categoriacientifica')),
                ('categoria_docente', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='RR_HH.categoriadocente')),
                ('nivel_escolaridad', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='RR_HH.nivelescolaridad')),
            ],
        ),
    ]
