# Generated by Django 5.0.2 on 2024-02-12 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RR_HH', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='trabajador',
            old_name='direcciion',
            new_name='direccion',
        ),
        migrations.AlterField(
            model_name='nivelescolaridad',
            name='descripcion',
            field=models.CharField(choices=[('9no_grado', '9no_Grado'), ('tecnico_medio', 'Técnico_Medio'), ('12mo_grado', '12mo_Grado'), ('universitario', 'Universitario')], max_length=250),
        ),
        migrations.AlterField(
            model_name='trabajador',
            name='carnet_identidad',
            field=models.IntegerField(unique=True),
        ),
    ]
